locations:
  input-dir: "."
  output-dir: "output"
  genome-fasta: "Chrpa1_1/Chrpa1_1_AssemblyScaffolds_2023-11-20.fasta"
  gff3-file: "Chrpa1_1/Chrpa1_1_FilteredModels1_2023-11-20.gff3"
  proteins-fasta: "desaturases.fasta"
  blast-output: "des_vs_Chrpa1_1.tsv"

general:
  species: "Chrysochromulina parva"
  species-short: "Chrpa1_1"
  evalue: 1e-05
  max-target-seqs: 10
  n-cores: 4