locations:
  input-dir: "."
  output-dir: "output"
  genome-fasta: "IsochDm2_1/IsochDm2_1_AssemblyScaffolds_2024-11-19.fasta"
  gff3-file: "IsochDm2_1/IsochDm2_1_FilteredModels1_2024-11-19.gff3"
  proteins-fasta: "polyketide_synthases.fasta"
  blast-output: "polyketide_synthases_vs_IsochDm2_1.tsv"

general:
  species: "Isochrysis galbana Dm2"
  species-short: "IsochDm2_1"
  evalue: 1e-5
  max-target-seqs: 10